### ISSUE TITLE
Engine Wishlist

### ISSUE THREAD

**Issue by LemmaEOF** [CottonMC/CottonScripting#1]
With stock Cotton Scripting, you can only really use JavaScript for scripting, and even then Nashorn is being deprecated. I want to see if we can get some JSR-223 engine addons to let people run other scripting languages. The primary ones we should get support for are:
- Lua (multiple options: LuaJ, LuaJIT, JNLua)
- Python (Jython for 2.7, but I can't find anything for 3.x)
  - [2.7 now available!](https://github.com/CottonMC/cotton-scripting-py2)
- SCarpet (could potentially run on top of Python?)
- Ruby (JRuby)

If anyone knows good JSR-223 compliant engines for any of these languages *that are under permissive license*, please send them here.

**Comment by Frontrider** [comment]
As discussed on discord, kotlin can be a good addition, as it's one of the few statically typed scripting languages.
Loading languages as addons could also be an option. If we know which ones are the ones that are actually used, than we can package those as defaults.

**Comment by LemmaEOF** [comment]
I was primarily thinking the addons route since we can just nest addons once we're happy with them and give folks an option to only pack the addons they want.

**Comment by Dolphin2Point1** [comment]
What I think would be easiest to implement is [ZenScript](https://github.com/CraftTweaker/ZenScript/tree/master). It is open-source, and was made for minecraft scripting.

**Comment by Juuxel** [comment]
Is there a JSR-223 engine for ZS?

**Comment by LemmaEOF** [comment]
No, there isn't. The problem with ZenScript is that it is *very* focused in on Minecrafting scripting and especially recipe tweaking, and so there's not really a general interpreter to run code that isn't related to Minecraft. It's not JSR-223 compliant, so it can't really be added.

**Comment by Dolphin2Point1** [comment]
Not sure. It might not be too hard if it wasn't JSR-223.

**Comment by Frontrider** [comment]
The system is designed to work with java script engines. Not being compliant, means that you can not reuse the same compat layers that we can use for every other language, and you have to re-implement every single thing ever added specifically for it, instead of working out of the box.

Zenscript did came up in my head as a good option for familiarity, but...

**Comment by Frontrider** [comment]
For zenscript's functionality, you'd implement your api once in java, (code that works from java as well), than it works from javascript, kotlin, lua, python etc...

**Comment by LemmaEOF** [comment]
Ultimately, it would likely require writing a new ZenScript interpreter from scratch that’s redesigned fundamentally to be a more abstract scripting language, and I don’t currently have time for that. I’d rather focus on making support for languages that already have compliant interpreters.

**Comment by LemmaEOF** [comment]
[scripting-cpython](https://github.com/scijava/scripting-cpython) seems like it *might* work for a python scripting lib, but I don't know Maven and so I can't get it to compile. If someone could help get me a jar of it so I could shadow it, that'd be aces.

**Comment by LemmaEOF** [comment]
…wait, I might be able to jitpack it.

**Comment by Frontrider** [comment]
It looks messy.

**Comment by LemmaEOF** [comment]
Yeah, it honestly does, but it's the only JSR223 python 3.x I can find.

**Comment by LemmaEOF** [comment]
~~in fact, the only other JSR223 python I can find *period* is by the same group and it looks to be set up in nearly exactly the same way.~~ edit: taking a more thorough look it looks a bit less messy, but I really wanna have python 3.x support instead of 2.7 so I don't know what to do

**Comment by LemmaEOF** [comment]
Alright: new problem with the python JSR223 stuff is that it's made with maven, not Gradle. This is an issue because it means that I can't use shadow for them, which basically defeats the entire point. I'm not sure what to do. I'll ask some others if they have any ideas.

**Comment by Frontrider** [comment]
Is it up on a branch?

**Comment by LemmaEOF** [comment]
I've almost got it ready! It turns out Loom/Loader will let you JiJ *any* jar, not just a Fabric mod. That means I can just `include` the jar from maven and it'll be fine!

**Comment by LemmaEOF** [comment]
https://github.com/CottonMC/cotton-scripting-py2/releases/tag/1.0.0 Jython version is now available. I'm gonna keep hunting and see if scripting-cpython is feasible to use for python 3.

**Comment by Nathan22211** [comment]
`java.lang.NoSuchMethodError: net.minecraft.class_3503.method_15195()V
	at io.github.cottonmc.cotton_scripting.impl.ScriptLoader.load(ScriptLoader.java:35) ~[cotton-scripting-1.2.0+1.14.jar:?]
	at net.fabricmc.fabric.api.resource.SimpleResourceReloadListener.reload(SimpleResourceReloadListener.java:49) ~[68094dc6-7cda-4706-8545-d7aa09864d4a.jar:?]
	at net.minecraft.class_4014.method_18368(class_4014.java:33) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_4014$$Lambda$2664/948517043.create(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.<init>(class_4014.java:46) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_4014.method_18369(class_4014.java:33) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_3304.method_18240(class_3304.java:131) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:151) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_3304.method_14478(class_3304.java:116) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1470) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:458) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_1132.method_3735(class_1132.java:98) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:129) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:615) [intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[04:19:20] [Server thread/ERROR]: This crash report has been saved to: C:\Users\carol\AppData\Roaming\.minecraft\crash-reports\crash-2019-10-16_04.19.20-server.txt
[04:19:20] [Server thread/INFO]: Stopping server
[04:19:20] [Server thread/INFO]: Saving players
[04:19:20] [Server thread/INFO]: Saving worlds
[04:19:20] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:546) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_1132.method_3723(class_1132.java:516) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:574) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:307) ~[intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [intermediary-fabric-loader-0.6.2+build.166-1.14.4.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`

**Comment by Pannoniae** [comment]
why

**Comment by Nathan22211** [comment]
There's MCscript written by Stervtus originally for compiling MCfunctions: https://github.com/Stevertus/mcscript which was written in JavaScript
And then there's Trident: https://github.com/Energyxxer/Trident-Language Another compiler that's written in Java by Energyxxer. both of these are under open source license's

**Comment by LemmaEOF** [comment]
A few updates, since it's been a while:
- scripting-cpython is not feasible to use, since it depends on the python installed on the host computer, and it's difficult passing objects between JVM and Python VM.
- I made an attempt to make a mod wrapper for Kotlin JSR-223, but without any luck due to weird classpath issues.
- I started working on a mod wrapper for Frege, but I need to put stuff onto maven local for it to work properly.
- Groovy has a `Compilable` and `Invocable` script engine, and Juuz is thinking of making a mod wrapper for it.
- LuaJ has a `Compilable` script engine but not an `Invocable` one, which means that it can't 100% be used. I might try PR'ing in `Invocable` support someday.

**Comment by Juuxel** [comment]
Frege? That's interesting.

**Comment by LemmaEOF** [comment]
Frege has a `Compilable` but not `Invocable` script engine. That should theoretically be fixable too.

**Comment by Frontrider** [comment]
Frege would be an interesting one. 

Fabric Kotlin should have the script engine already in there.

**Comment by Juuxel** [comment]
> Groovy has a `Compilable` and `Invocable` script engine, and Juuz is thinking of making a mod wrapper for it.

That wrapper is now done: https://github.com/CottonMC/CottonScripting-Groovy

**Comment by LemmaEOF** [comment]
@Frontrider Fabric Kotlin should absolutely *not* have the script engine already in here, because it would *triple* the size of the mod (because it'd need the *entire* kotlin compiler) and only LibCD and Cotton Scripting would use it.

**Comment by Frontrider** [comment]
That was forgelin, yeah. This one does something else.

**Comment by Nathan22211** [comment]
now i'm beginning to miss this just looking at it

**Comment by sylv256** [comment]
> now i'm beginning to miss this just looking at it

I might work on something like this in the future.

**Comment by LemmaEOF** [comment]
I mean feel free to PR to this if you wanna extend it, I got myself burnt out on minecraft modding again (and I also wanted to try and make Chase which probably wouldn't work with Parchment at all oops)
